### ISSUE TITLE
CSS Issues

### ISSUE THREAD

**Issue by nickhamze** [sortarad/peculiarpointer#1]
Hey @Mamaduka I tried it out and the method you implemented it is great. No problems there. 

I did have a bit of trouble with the CSS (when using an SVG). When I first tried it it was generated this CSS but no cursor was outputted:
<img width="324" alt="Screen Shot 2020-12-01 at 5 15 18 AM" src="https://user-images.githubusercontent.com/158918/100743643-301f2c80-33a2-11eb-9400-6a4d846076a7.png">

But then I went back to our WordPress plugin and saw that the CSS there was a bit different, and when I tried that CSS it worked:
<img width="322" alt="Screen Shot 2020-12-01 at 5 16 31 AM" src="https://user-images.githubusercontent.com/158918/100743659-357c7700-33a2-11eb-9482-58b30f24c426.png">

We should also add this line of CSS to make the anchor tags take the new cursor. This seems cleaner than an !important.

a {
    cursor: unset;
}

**Comment by Mamaduka** [comment]
The first issue is fixed via 545da75.

The second one isn't doable via the style attribute and it seems that adding `!important` also has no effect.
